### ISSUE TITLE
Error: Cannot find module './keycloak-server'

### ISSUE THREAD

**Issue by JesseCarlos** [Procempa/meteor-keycloak-auth#6]
I created a simple meteor project to test keycloak-auth and I have this error in console:

> Error:
 Cannot find module './keycloak-server'
W20161227-02:11:30.935(-2)? (STDERR)     at Function.require.resolve (packages/modules-runtime.js:129:19)
W20161227-02:11:30.936(-2)? (STDERR)     at Module.resolve (packages/modules-runtime.js:81:25)
W20161227-02:11:30.936(-2)? (STDERR)     at Module.Mp.import (/home/jesse/.meteor/packages/modules/.0.7.7.1m2ukcu++os+web.browser+web.cordova/npm/node_modules/reify/lib/runtime.js:61:29)
W20161227-02:11:30.936(-2)? (STDERR)     at meteorInstall.node_modules.meteor.procempa:keycloak-auth.server-main.js (packages/procempa:keycloak-auth/server-main.js:1:1)
W20161227-02:11:30.936(-2)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:181:9)
W20161227-02:11:30.936(-2)? (STDERR)     at require (packages/modules-runtime.js:106:16)
W20161227-02:11:30.936(-2)? (STDERR)     at /home/jesse/workspace/work_directory_personal/meteor/teste/.meteor/local/build/programs/server/packages/procempa_keycloak-auth.js:16981:15

I just added the package and nothing more. What I did wrong?

**Comment by af6140** [comment]
Go the same error.

**Comment by jamalazza** [comment]
same here

**Comment by tomjackman** [comment]
@silveirado Is it possible to take a look at fixing this small issue?
